# Generated by Django 6.0.6 on 2026-07-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='document_type',
            field=models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('CE', 'Carné de Extranjería'), ('PASAPORTE', 'Pasaporte'), ('SIN_DOCUMENTO', 'Sin documento')], default='SIN_DOCUMENTO', max_length=15),
        ),
    ]
