# Generated by Django 6.0.6 on 2026-08-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_customer_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='document_type',
            field=models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('CE', 'Foreign Resident Card'), ('PASAPORTE', 'Passport'), ('SIN_DOCUMENTO', 'No document')], default='SIN_DOCUMENTO', max_length=15),
        ),
    ]
