# Generated by Django 6.0.6 on 2026-07-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='is_cash',
            field=models.BooleanField(default=False),
        ),
    ]
