# Generated by Django 6.0.6 on 2026-07-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_productcategory_image_productsubcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
