# Generated by Django 6.0.6 on 2026-08-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_paymentmethod_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_value', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='productcategory',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=2, unique=True),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=4, unique=True),
        ),
    ]
