# Generated by Django 6.0.6 on 2026-07-07 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0002_paymentmethod_is_cash'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('receipt_type', models.CharField(choices=[('BOLETA', 'Boleta'), ('FACTURA', 'Factura'), ('RECIBO', 'Recibo'), ('NONE', 'Ninguno')], default='NONE', max_length=20)),
                ('payment_status', models.CharField(choices=[('PREPAID', 'Pagado por adelantado'), ('CASH_ON_ORDER', 'Al contado'), ('INSTALLMENTS', 'En partes'), ('CASH_ON_DELIVERY', 'Contraentrega')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('PEN', 'Soles (PEN)'), ('USD', 'Dólares (USD)')], default='PEN', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('pen_equivalent_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='catalogs.expensecategory')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='catalogs.paymentmethod')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='contacts.supplier')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
