# Generated by Django 6.0.6 on 2026-08-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('PEN', 'Soles (PEN)'), ('USD', 'US Dollars (USD)')], default='PEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_status',
            field=models.CharField(choices=[('PREPAID', 'Prepaid'), ('CASH_ON_ORDER', 'Cash on order'), ('INSTALLMENTS', 'In installments'), ('CASH_ON_DELIVERY', 'Cash on delivery')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='receipt_type',
            field=models.CharField(choices=[('BOLETA', 'Simplified receipt'), ('FACTURA', 'Invoice'), ('RECIBO', 'Voucher'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
    ]
