# Generated by Django 6.0.6 on 2026-08-06 14:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorydamage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pack_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('pack_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pack_price', to='inventory.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
