# Generated by Django 6.0.6 on 2026-07-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_closingpin_processdate_cashregistersession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryexit',
            name='unit_cost_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
