# Generated by Django 6.0.6 on 2026-07-13 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_inventoryexit_unit_cost_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('NOTA_VENTA', 'Nota de Venta'), ('BOLETA', 'Boleta de Venta'), ('FACTURA', 'Factura'), ('NOTA_CREDITO', 'Nota de Crédito'), ('NOTA_DEBITO', 'Nota de Débito')], max_length=15, unique=True)),
                ('series', models.CharField(max_length=10)),
                ('next_correlativo', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SaleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('NOTA_VENTA', 'Nota de Venta'), ('BOLETA', 'Boleta de Venta'), ('FACTURA', 'Factura'), ('NOTA_CREDITO', 'Nota de Crédito'), ('NOTA_DEBITO', 'Nota de Débito')], max_length=15)),
                ('series', models.CharField(max_length=10)),
                ('correlativo', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ISSUED', 'Emitido'), ('VOIDED', 'Anulado')], default='ISSUED', max_length=10)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('customer_document_type', models.CharField(blank=True, max_length=20)),
                ('customer_document_number', models.CharField(blank=True, max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='pos.saledocument')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='pos.sale')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('series', 'correlativo'), name='unique_series_correlativo')],
            },
        ),
    ]
