# Generated by Django 6.0.6 on 2026-07-13 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_documentseries_sale_is_voided_saledocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closing_pin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ClosingPin',
        ),
        migrations.AddField(
            model_name='registerclosing',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closings_authorized', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registerclosing',
            name='category_breakdown',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='registerclosing',
            name='document_breakdown',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='registerclosing',
            name='product_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
