# Generated by Django 6.0.6 on 2026-08-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_adminpin_delete_closingpin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentseries',
            name='document_type',
            field=models.CharField(choices=[('NOTA_VENTA', 'Sales Receipt'), ('BOLETA', 'Receipt'), ('FACTURA', 'Invoice'), ('NOTA_CREDITO', 'Credit Note'), ('NOTA_DEBITO', 'Debit Note')], max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='draftsaleline',
            name='movement_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('GIFT', 'Gift / Complimentary')], default='SALE', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventoryexit',
            name='movement_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('GIFT', 'Gift / Complimentary')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registerclosing',
            name='closing_type',
            field=models.CharField(choices=[('X', 'X Closing (partial)'), ('Z', 'Z Closing (end of day)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='saledocument',
            name='document_type',
            field=models.CharField(choices=[('NOTA_VENTA', 'Sales Receipt'), ('BOLETA', 'Receipt'), ('FACTURA', 'Invoice'), ('NOTA_CREDITO', 'Credit Note'), ('NOTA_DEBITO', 'Debit Note')], max_length=15),
        ),
        migrations.AlterField(
            model_name='saledocument',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('VOIDED', 'Voided')], default='ISSUED', max_length=10),
        ),
    ]
