# Generated by Django 6.0.6 on 2026-08-05 01:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_alter_documentseries_document_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='saledocument',
            name='unique_series_correlativo',
        ),
        migrations.RenameField(
            model_name='documentseries',
            old_name='next_correlativo',
            new_name='next_sequence_number',
        ),
        migrations.RenameField(
            model_name='saledocument',
            old_name='correlativo',
            new_name='sequence_number',
        ),
        migrations.AddConstraint(
            model_name='saledocument',
            constraint=models.UniqueConstraint(fields=('series', 'sequence_number'), name='unique_series_sequence_number'),
        ),
    ]
