# Generated by Django 6.0.6 on 2026-07-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('source', models.CharField(default='SUNAT', max_length=100)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'daily exchange rate',
                'verbose_name_plural': 'daily exchange rates',
                'ordering': ['-date'],
            },
        ),
    ]
